Repository teorth/equational_theories, pull requests merged in 2024-09, with the labels that each got.

#7 Add enough implications and counter-examples to place (3)
  equational_theories/Basic.lean
Labels: awaiting-merge

#28 Create labels-from-comments.yml
  .github/workflows/labels-from-comments.yml
Labels: WIP

#39 SUBGRAPH: Prove that 38 and 42 are equivalent
  equational_theories/Subgraph.lean
Labels: awaiting-review

#49 SUBGRAPH: Prove 5 does not imply 42, 43, 4513
  equational_theories/Subgraph.lean
Labels: awaiting-review

#53 SUBGRAPH: Show 40 does not imply 3, 8, 42, 43, 4512; and 4, 387, 4582 does not imply 40
  equational_theories/Subgraph.lean
Labels: awaiting-review

#23 Solutions for 53,905 cases by substituting+renaming variables
  equational_theories.lean
  equational_theories/SimpleRewrites.lean
  equational_theories/SimpleRewrites/README.md
  equational_theories/SimpleRewrites/src/equations.txt
  equational_theories/SimpleRewrites/src/find_redundant.py
  equational_theories/SimpleRewrites/src/find_simple_rewrites.py
  equational_theories/SimpleRewrites/src/utils.py
  equational_theories/SimpleRewrites/theorems/Rewrite_uw.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_vu.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_vu_wx.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_vu_wy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_vu_wz.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_vu_wz_yx_zy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_vu_wz_zx.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_vu_wz_zy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_wx.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_wy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_wz.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_wz_yx_zy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_wz_zx.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uw_wz_zy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_ux.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_ux_vu.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uy_vu.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uz.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_uz_vu.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_vu.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_vw.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_vx.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_vy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_vz.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_wx.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_wy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_wz.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_wz_yx_zy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_wz_zx.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_wz_zy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_yx.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_yx_zy.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_zx.lean
  equational_theories/SimpleRewrites/theorems/Rewrite_zy.lean
Labels: awaiting-CI

#70 [TEST] Propose PR Workflow
  README.md
Labels: do-not-merge

#100 Cache build artefacts in blueprint workflow
  .github/workflows/blueprint.yml
  blueprint/lean_decls
Labels: do-not-merge

#101 SUBGRAPH: prove implications/anti-implications between 23 and other equations
  equational_theories/Subgraph.lean
Labels: awaiting-review

#118 [TEST] Awaiting Review Workflow
  README.md
Labels: awaiting-review, do-not-merge

#130 Let @[equational_result] handle facts
  equational_theories/AllEquations.lean
  equational_theories/Conjecture.lean
  equational_theories/EquationalResult.lean
  equational_theories/ParseImplications.lean
  equational_theories/SmallMagmas.lean
  equational_theories/Subgraph.lean
Labels: awaiting-CI

#123 Codyroux/compactness
  Unidecode-1.3.8-py3-none-any.whl
  blueprint/src/chapter/intro.tex
  equational_theories.lean
  equational_theories/Compactness.lean
  equational_theories/Completeness.lean
  equational_theories/FreeMagma.lean
Labels: awaiting-author
