Repository teorth/equational_theories, pull requests merged in 2024-10, with the labels that each got.

#154 SUBGRAPH: Show that 1689 implies (and is in fact equivalent to) 2 (Theorem 4.5)
  blueprint/src/chapter/implications.tex
  equational_theories/Subgraph.lean
Labels: awaiting-review

#126 Add Lean code for computing the transitive closure
  CONTRIBUTING.md
  equational_theories/Closure.lean
  equational_theories/Conjecture.lean
  equational_theories/EquationalResult.lean
  equational_theories/FreeMagma.lean
  equational_theories/ParseImplications.lean
  equational_theories/Subgraph.lean
  scripts/extract_implications.lean
Labels: awaiting-review

#135 feat: add preorder on magma laws
  blueprint/src/chapter/general_implications.tex
  equational_theories/Completeness.lean
  equational_theories/FreeMagma.lean
  equational_theories/Preorder.lean
Labels: awaiting-review

#195 INFINITE: State and prove Theorem 2.37 (Equation 5105 has no non-trivial finite models) in Lean
  blueprint/src/chapter/equations.tex
  equational_theories/InfModel.lean
Labels: awaiting-review

#197 extact_implications: add --equivalence_creators flag to unknowns subcommand
  README.md
  scripts/extract_implications.lean
Labels: awaiting-review

#222 Revert "Codyroux/derivation preserves size"
  equational_theories.lean
  equational_theories/OrderMetatheorem.lean
Labels: awaiting-CI

#240 feat: scoped instances and notation priority
  equational_theories/Completeness.lean
  equational_theories/Magma.lean
Labels: awaiting-review

#258 fix path filters
  .github/workflows/blueprint.yml
Labels: awaiting-CI

#155 Free magma universal properties
  equational_theories/Completeness.lean
  equational_theories/FreeMagma.lean
  equational_theories/MagmaLaw.lean
Labels: awaiting-review

#304 chore: make all Python scripts in `scripts/` executable
  equational_theories/Generated/All4x4Tables/src/check_correct.py
  equational_theories/Generated/All4x4Tables/src/check_redundant.py
  equational_theories/Generated/All4x4Tables/src/double_check_3x3.py
  equational_theories/Generated/All4x4Tables/src/drive_c_parallel.py
  equational_theories/Generated/All4x4Tables/src/dump_tables.py
  equational_theories/Generated/All4x4Tables/src/generate_lean.py
  equational_theories/Generated/All4x4Tables/src/prune.py
  equational_theories/Generated/FinSearch/src/finite_magma.py
  equational_theories/Generated/FinSearch/src/finsearch.py
  equational_theories/Generated/FinSearch/src/generate_lean.py
  equational_theories/Generated/FinSearch/src/parser.py
  equational_theories/Generated/FinitePoly/src/finite_poly_generate_lean.py
  equational_theories/Generated/FinitePoly/src/generate_refutations.py
  equational_theories/Generated/FinitePoly/src/utils.py
  equational_theories/Generated/SimpleRewrites/src/find_redundant.py
  equational_theories/Generated/SimpleRewrites/src/find_simple_rewrites.py
  equational_theories/Generated/SimpleRewrites/src/utils.py
  equational_theories/Generated/TrivialBruteforce/src/generate_refutations.py
  equational_theories/Generated/VampireProven/src/vampire_proofs.py
  scripts/customize_template.py
  scripts/find_dual.py
  scripts/find_equation_id.py
  scripts/find_powerful_theorems.py
  scripts/generate_dashboard.py
  scripts/generate_eqs_list.py
  scripts/generate_image.py
  scripts/generate_most_wanted_list.py
  scripts/generate_z3_counterexample.py
  scripts/outcomes_to_image.py
  scripts/process_implications.py
Labels: do-not-merge

#318 Equation953_implies_Equation2 refactored
  equational_theories/Subgraph.lean
Labels: awaiting-review

#319 easy superficial refactoring
  equational_theories/Subgraph.lean
Labels: awaiting-review

#320 just cosmetic changes
  equational_theories/Subgraph.lean
Labels: awaiting-review

#323 if underscores are desirable then use them more efficiently
  equational_theories/Subgraph.lean
Labels: awaiting-review

#348 links
  README.md
  blueprint/src/chapter/implications.tex
  blueprint/src/chapter/infinite_models.tex
  equational_theories/Generated/All4x4Tables/src/generate_combined_refutations.sh
Labels: awaiting-CI

#387 Fix_links
  README.md
  blueprint/src/chapter/infinite_models.tex
  blueprint/src/chapter/intro.tex
  blueprint/src/print.pdf
  home_page/index.md
Labels: awaiting-CI

#400 Use cleveref
  blueprint/src/chapter/abstract_nonsense.tex
  blueprint/src/chapter/constant.tex
  blueprint/src/chapter/counterexamples.tex
  blueprint/src/chapter/egraphs.tex
  blueprint/src/chapter/equations.tex
  blueprint/src/chapter/general_implications.tex
  blueprint/src/chapter/implications.tex
  blueprint/src/chapter/infinite_models.tex
  blueprint/src/chapter/intro.tex
  blueprint/src/chapter/metatheorems_from_invariants.tex
  blueprint/src/print.tex
  blueprint/src/web.tex
Labels: awaiting-review

#399 Extract implications: unknowns subcommands --duality flag
  README.md
  data/outstanding_3op_implications.txt
  data/unknowns_10_06.txt
  data/unknowns_10_07.json
  equational_theories/Closure.lean
  scripts/extract_implications.lean
Labels: awaiting-review

#202 State and prove Theorem 2.36
  blueprint/src/chapter/infinite_models.tex
  equational_theories/Equations.lean
  equational_theories/InfModel.lean
  equational_theories/Subgraph.lean
Labels: awaiting-review

#432 [TEST] New `propose #PR_NUMBER` workflow
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: do-not-merge

#435 [TEST] Make `propose PR` workflow more flexible
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: do-not-merge

#427 Equations command modification
  blueprint/src/chapter/metatheorems_from_invariants.tex
  equational_theories/EquationLawConversion.lean
  equational_theories/EquationsCommand.lean
  equational_theories/FreeMagma.lean
  equational_theories/MagmaLaw.lean
  equational_theories/Preorder.lean
Labels: awaiting-review

#429 Export equations
  equational_theories/MagmaLaw.lean
  lakefile.toml
  scripts/export_equations.lean
Labels: awaiting-review

#453 Asterix
  CONTRIBUTING.md
  blueprint/src/chapter/abstract_nonsense.tex
  blueprint/src/chapter/asterix.tex
  blueprint/src/chapter/equations.tex
  blueprint/src/content.tex
  blueprint/src/print.pdf
Labels: awaiting-CI

#454 subgraph style
  equational_theories/Subgraph.lean
Labels: do-not-merge

#455 the same typo was actually in three places
  home_page/implications/script.js
Labels: do-not-merge

#448 improved equation command
  equational_theories/EquationsCommand.lean
Labels: awaiting-review

#471 Typo fix in Definition 7.1 in asterix.tex
  blueprint/src/chapter/asterix.tex
Labels: awaiting-review, project-task

#488 Typo fix in Lemma 1.10. (Pushforward) in intro.tex
  blueprint/src/chapter/intro.tex
Labels: awaiting-review

#484 Switch find_confluent_equations.py to use e-graphs
  equational_theories/Generated/Confluence/confluent_equations.txt
  equational_theories/Generated/Confluence/src/find_confluent_equations.py
Labels: awaiting-review

#497 Add equations 1086, 2497, 2541 to Confluence.lean
  equational_theories/Confluence.lean
Labels: awaiting-review

#421 lean4lean python script
  .github/workflows/blueprint.yml
  scripts/lean4lean_checker/.gitignore
  scripts/lean4lean_checker/README.md
  scripts/lean4lean_checker/__init__.py
  scripts/lean4lean_checker/main.py
  scripts/lean4lean_checker/requirements.txt
Labels: awaiting-review

#522 Fix issue #507
  home_page/implications/index.html
  home_page/implications/script.js
Labels: awaiting-review

#496 DATA: Add examples to smallest_magma.txt
  data/small_magma_examples.txt
  data/smallest_magma.txt
  data/smallest_magma_examples.txt
  scripts/gather_small_magmas.py
Labels: awaiting-review

#529 EQUATION_EXPLORER: List smallest non-trivial finite magmas associated to each equation
  home_page/implications/index.html
  home_page/implications/script.js
  scripts/generate_equation_implication_js.py
Labels: awaiting-review

#526 Lifting magma families
  blueprint/src/chapter/metatheorems_from_invariants.tex
  equational_theories/Equations/Command.lean
  equational_theories/Generated.lean
  equational_theories/Generated/InvariantMetatheoremNonimplications.lean
  equational_theories/Generated/InvariantMetatheoremNonimplications/README.md
  equational_theories/Generated/InvariantMetatheoremNonimplications/instLiftingMagmaFamilyLeftProj_counterexamples.lean
  equational_theories/Generated/InvariantMetatheoremNonimplications/instLiftingMagmaFamilyList_counterexamples.lean
  equational_theories/Generated/InvariantMetatheoremNonimplications/instLiftingMagmaFamilyMultiset_counterexamples.lean
  equational_theories/Generated/InvariantMetatheoremNonimplications/instLiftingMagmaFamilyRightProj_counterexamples.lean
  equational_theories/LiftingMagmaFamilies.lean
  equational_theories/LiftingMagmaFamiliesCounterexamples.lean
  equational_theories/MagmaLaw.lean
  lakefile.toml
  scripts/export_equations.lean
Labels: awaiting-review

#556 Bold highlight equations with commentary (#547)
  home_page/implications/script.js
Labels: awaiting-review

#560 Add button to hide fully-solved equations (#546)
  home_page/implications/index.html
  home_page/implications/script.js
Labels: awaiting-review

#564 More-commentary
  blueprint/src/chapter/abstract_nonsense.tex
  blueprint/src/chapter/greedy.tex
  blueprint/src/print.pdf
  commentary/Equation1648.md
  commentary/Equation1659.md
  commentary/Equation2000.md
  commentary/Equation2126.md
  equational_theories/Completeness.lean
Labels: awaiting-CI

#589 add commentary
  commentary/Equation1289.md
  commentary/Equation1447.md
  commentary/Equation41.md
  commentary/Equation46.md
  commentary/Equation713.md
Labels: awaiting-CI

#601 add missing conjectures
  equational_theories/Conjectures.lean
Labels: awaiting-CI

#599 tree-based proof that 206 anti-implies 1648
  equational_theories.lean
  equational_theories/ThreeC2.lean
Labels: awaiting-review

#605 ThreeC3: Disprove Equation1648, not Equation1684
  equational_theories/ThreeC2.lean
Labels: awaiting-review

#615 new conjectures from greedy algorithm
  equational_theories/Conjectures.lean
Labels: awaiting-CI

#622 add 1841 conjecture
  equational_theories/Conjectures.lean
Labels: awaiting-CI

#618 a proof that our set of laws/equations is actually complete
  equational_theories.lean
  equational_theories/Equations/LawsComplete.lean
  equational_theories/RArray.lean
Labels: awaiting-review

#632 add 879 conjecture
  equational_theories/Conjectures.lean
Labels: awaiting-CI

#639 Use tree model to show that 1841 !=> 203
  equational_theories/ThreeC2.lean
Labels: awaiting-review

#670 commentary and conjectures
  commentary/Equation1729.md
  commentary/Equation917.md
  equational_theories/Conjectures.lean
Labels: awaiting-CI

#442 Prove Theorem 3.11
  blueprint/src/chapter/infinite_models.tex
  equational_theories/FreeMagma.lean
  equational_theories/InfModel.lean
Labels: awaiting-review

#679 Remove 1841 conjecture; unify 73 conjectures; improve link to 3342 conjecture
  equational_theories/Conjectures.lean
Labels: awaiting-CI

#716 temporarily suspending some conjectures to record FME instructions
  equational_theories/Conjectures.lean
Labels: awaiting-CI

#730 add bibitems to previous Moufang loop work
  blueprint/src/references.bib
Labels: awaiting-CI

#741 Add a script for path-finding in the implications graph
  scripts/explain_implication.py
  scripts/extract_implications.lean
Labels: awaiting-review

#746 write new blueprint chapter
  blueprint/src/chapter/854.tex
  blueprint/src/chapter/equations.tex
  blueprint/src/content.tex
  blueprint/src/print.xdv
  full_entries.json
  scripts/full_entries.json
Labels: awaiting-CI
