Repository teorth/equational_theories, pull requests merged in 2024-11, with the labels that each got.

#766 Add a "Show Proof" button to the equation explorer.
  .github/workflows/blueprint.yml
  equational_theories/EquationalResult.lean
  full_entries.json
  home_page/implications/find_equation_id.js
  home_page/implications/index.html
  home_page/implications/script.js
  home_page/implications/show_proof.html
  scripts/generate_equation_implication_js.py
Labels: awaiting-review

#810 add 1323 proof
  blueprint/src/chapter/1323.tex
  blueprint/src/content.tex
Labels: awaiting-CI

#819 1516-proof
  blueprint/src/chapter/1516.tex
  blueprint/src/content.tex
Labels: awaiting-CI

#822 fix 1323
  blueprint/src/chapter/1323.tex
Labels: awaiting-CI

#839 add finite conjectures
  equational_theories/Conjectures.lean
Labels: awaiting-CI

#854 update commentary on 476, 503
  commentary/Equation476.md
  commentary/Equation503.md
Labels: awaiting-CI

#867 Fix-blueprint
  blueprint/src/content.tex
  equational_theories/Conjectures.lean
Labels: awaiting-CI

#884 Contributions - Tao
  paper/contributions.md
Labels: contribution

#891 [CONTRIBUTIONS]: Pietro Monticone
  paper/contributions.md
  paper/contributions.tex
Labels: contribution

#909 chore: bump mathlib
  blueprint/src/chapter/1729.tex
  blueprint/src/chapter/854.tex
  blueprint/src/chapter/equations.tex
  blueprint/src/chapter/implications.tex
  blueprint/src/chapter/infinite_magma_constructions.tex
  lake-manifest.json
  paper/main.pdf
Labels: awaiting-CI

#896 [CONTRIBUTIONS]: Fan Zheng
  paper/contributions.md
Labels: contribution

#938 906-stuff
  blueprint/src/chapter/906.tex
  commentary/Equation906.md
  equational_theories/Conjectures.lean
  paper/constructions.tex
  paper/main.pdf
  paper/numbering.tex
Labels: awaiting-CI
